/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package uiproject;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FormCheckout extends javax.swing.JFrame {

    Socket s;
    ArrayList<Keranjang> listKeranjang = new ArrayList<>();

    /**
     * Creates new form FormCheckout
     */
    public FormCheckout() {
        try {
            initComponents(); 
            usernameProfile.setText(FormLogin.user);
            s = new Socket("localhost", 6000);

            DataOutputStream out = new DataOutputStream(s.getOutputStream());
            out.writeBytes("GET_KERANJANG\n");

            BufferedReader in = new BufferedReader(new InputStreamReader(s.getInputStream()));
            String receivedData = in.readLine();

            ArrayList<Keranjang> parsedList = parseStringToList(receivedData);
            loadData(parsedList);
            tampilkanKeTabel();
            tampilkanTotalCheckout();
            
            this.setLocationRelativeTo(null);
            this.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal inisialisasi form: " + e.getMessage());
        }

    }

    private void loadData(ArrayList<Keranjang> data) {
        listKeranjang.clear();
        listKeranjang.addAll(data);
    }

    private ArrayList<Keranjang> parseStringToList(String data) {
        ArrayList<Keranjang> result = new ArrayList<>();
        
        String[] keranjangStrings = data.split("#"); // pisah antar keranjang
        for(String keranjangStr : keranjangStrings) {
            if (!keranjangStr.trim().isEmpty()) {
                String[] fields = keranjangStr.split("\\|");
                
                String username = fields[0];
                String creatorName = fields[1];
                String eventName = fields[2];
                String jenis = fields[3];
                double price = Double.parseDouble(fields[4]);
                int quantity = Integer.parseInt(fields[5]);
                double total = Double.parseDouble(fields[6]);
                
                Keranjang k = new Keranjang(username, creatorName, eventName, jenis, price, quantity, total);

                if (FormLogin.user.equals(username)) {
                    result.add(k);
                }
            }
        }
        return result;
    }

    private void tampilkanKeTabel() {
        DefaultTableModel model = (DefaultTableModel) tabelCekout.getModel();
        model.setRowCount(0); // clear existing rows

        for (Keranjang k : listKeranjang) {

            Object[] row = {
                k.getCreatorName(),
                k.getEventName(),
                k.getJenis(),
                k.getPrice(),
                k.getQuantity(),
                k.getTotal()
                // setelah stock ini ada kolom untuk aksi, yang nantinya terisi dengan button untuk delete tiket yang batal dibeli
            };
            model.addRow(row);
        }
    }
    
    private void tampilkanTotalCheckout() {
        double total = 0;
        for (Keranjang k : listKeranjang) {
            double subtotal = k.getTotal();
            total += subtotal;
        }
        labelTotal.setText(Double.toString(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEvents = new javax.swing.JButton();
        btnEvents1 = new javax.swing.JButton();
        usernameProfile = new javax.swing.JLabel();
        gambarProfile = new javax.swing.JLabel();
        btnEvents2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelCekout = new javax.swing.JTable();
        btnCheckout = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WATCHIFY");

        btnSearch.setText("search");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnEvents.setBackground(new java.awt.Color(153, 0, 51));
        btnEvents.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEvents.setForeground(new java.awt.Color(255, 255, 255));
        btnEvents.setText("EVENTS");
        btnEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventsActionPerformed(evt);
            }
        });

        btnEvents1.setBackground(new java.awt.Color(160, 89, 104));
        btnEvents1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEvents1.setForeground(new java.awt.Color(255, 255, 255));
        btnEvents1.setText("KERANJANG");

        usernameProfile.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        usernameProfile.setForeground(new java.awt.Color(255, 255, 255));
        usernameProfile.setText("nama Pengguna");

        gambarProfile.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        gambarProfile.setForeground(new java.awt.Color(255, 255, 255));
        gambarProfile.setText("gambar_barang");
        gambarProfile.setToolTipText("");

        btnEvents2.setBackground(new java.awt.Color(153, 0, 51));
        btnEvents2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEvents2.setForeground(new java.awt.Color(255, 255, 255));
        btnEvents2.setText("HISTORY");
        btnEvents2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvents2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnEvents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEvents1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEvents2)
                .addGap(47, 47, 47)
                .addComponent(usernameProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gambarProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernameProfile)
                        .addComponent(gambarProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)
                        .addComponent(btnEvents)
                        .addComponent(btnEvents1)
                        .addComponent(btnEvents2)))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Total Harga :");

        tabelCekout.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Pembuat/Toko", "Nama Produk", "Jenis", "Harga Satuan", "Kuantitas", "Harga Total", "Aksi"
            }
        ));
        jScrollPane1.setViewportView(tabelCekout);

        btnCheckout.setBackground(new java.awt.Color(153, 0, 51));
        btnCheckout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("Checkout");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTotal.setText("xxxx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTotal)
                        .addGap(135, 135, 135)
                        .addComponent(btnCheckout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckout)
                    .addComponent(jLabel6)
                    .addComponent(labelTotal))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
        null,
        "Total checkout: Rp " + labelTotal.getText() + "\nApakah Anda yakin ingin checkout?",
        "Konfirmasi Checkout",
        JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == JOptionPane.YES_OPTION) {
            try {
            
                s = new Socket("localhost", 6000);

                DataOutputStream out = new DataOutputStream(s.getOutputStream());
                out.writeBytes("CHECKOUT " + FormLogin.user + "\n");

                BufferedReader in = new BufferedReader(new InputStreamReader(s.getInputStream()));
                String receivedData = in.readLine();
                ArrayList<Keranjang> parsedList = parseStringToList(receivedData);
                loadData(parsedList);
                tampilkanKeTabel();
                tampilkanTotalCheckout();
            
                this.setLocationRelativeTo(null);
                this.setVisible(true);
                
                //Setelah Berhasil Checkout, masuk ke list history
                
                JOptionPane.showMessageDialog(null, "Checkout berhasil!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal melakukan proses checkout: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Checkout dibatalkan.");
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed


    private void btnEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventsActionPerformed
        // TODO add your handling code here:

        try {
            this.dispose();

            FormListTickets listTicket = new FormListTickets();
            listTicket.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FormCheckout.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEventsActionPerformed

    private void btnEvents2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvents2ActionPerformed
        // TODO add your handling code here:
        this.dispose();

        FormHistory histori = new FormHistory();
        histori.setVisible(true);
    }//GEN-LAST:event_btnEvents2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCheckout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnEvents;
    private javax.swing.JButton btnEvents1;
    private javax.swing.JButton btnEvents2;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel gambarProfile;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tabelCekout;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel usernameProfile;
    // End of variables declaration//GEN-END:variables
}
